version: '3.8'

services:

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - 6379:6379
      - 8001:8001  # Expose RedisInsight port

  app:
    build: .
    restart: always
    working_dir: /elt-platform
    volumes:
      - "/Users/AbdulbakrSiddique/Desktop/Programmers Force/ELT:/elt-platform"
    ports:
      - 3000:3000
    depends_on:
      - redis
